/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.14.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as backend_subscriptions_subscriptions from "../backend/subscriptions/subscriptions.js";
import type * as backend_subscriptions_usersubscriptions from "../backend/subscriptions/usersubscriptions.js";
import type * as backend_users_savedcalendars from "../backend/users/savedcalendars.js";
import type * as backend_users_users from "../backend/users/users.js";
import type * as backend_workspace_boards from "../backend/workspace/boards.js";
import type * as backend_workspace_lists from "../backend/workspace/lists.js";
import type * as backend_workspace_tempshareds from "../backend/workspace/tempshareds.js";
import type * as backend_workspace_workspace from "../backend/workspace/workspace.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  "backend/subscriptions/subscriptions": typeof backend_subscriptions_subscriptions;
  "backend/subscriptions/usersubscriptions": typeof backend_subscriptions_usersubscriptions;
  "backend/users/savedcalendars": typeof backend_users_savedcalendars;
  "backend/users/users": typeof backend_users_users;
  "backend/workspace/boards": typeof backend_workspace_boards;
  "backend/workspace/lists": typeof backend_workspace_lists;
  "backend/workspace/tempshareds": typeof backend_workspace_tempshareds;
  "backend/workspace/workspace": typeof backend_workspace_workspace;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
